#!/bin/bash

# Text formatting
bold="\e[1m"
normal="\e[0m"
white="\e[0;39m"
green="\e[1;32m"

# Get load averages
IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(cat /proc/loadavg | awk '{ print $1,$2,$3 }')

# Get free memory
IFS=" " read USED AVAIL TOTAL <<<$(free -htm | grep "Mem" | awk {'print $3,$7,$2'})

# Get processes
PROCESS=`ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }'`
PROCESS_ALL=`echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
PROCESS_ROOT=`echo "$PROCESS"| grep root | awk {'print $2'}`
PROCESS_USER=`echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`

# Get processors
PROCESSOR_NAME=`grep "model name" /proc/cpuinfo | cut -d ' ' -f3- | awk {'print $0'} | head -1`
PROCESSOR_COUNT=`grep -ioP 'processor\t:' /proc/cpuinfo | wc -l`


echo -e "
${white}${bold}system info${normal}
$white  hostname       $white`hostname`
$white  distribution   $white`cat /etc/*release | grep "PRETTY_NAME" | cut -d "=" -f 2- | sed 's/"//g'`
$white  kernel         $white`uname -sr`

$white  uptime         $white`uptime -p`
$white  load           $green$LOAD1$white (1m), $green$LOAD5$white (5m), $green$LOAD15$white (15m)
$white  processes      $white$green$PROCESS_ROOT$white (root), $green$PROCESS_USER$white (user), $green$PROCESS_ALL$white (total)

$white  cpu            $white$PROCESSOR_NAME ($green$PROCESSOR_COUNT$white vCPU)
$white  memory         $green$USED$white used, $green$AVAIL$white avail, $green$TOTAL$white total$white"

echo